version: '3.7'
services:
  soveltuvuustesti-rahti:
    container_name: soveltuvuustesti-rahti
    command: gunicorn --bind 0.0.0.0:8081 'api.api:app'
    env_file: .env
    build:
      context: ..
      dockerfile: ./docker/Dockerfile_rahti
    expose:
      - 8081
    depends_on:
      - soveltuvuustesti-db-rahti

  soveltuvuustesti-db-rahti:
    image: postgres:15
    restart: always
    container_name: soveltuvuustesti-db-rahti
    env_file: .env
    volumes:
      - ./dbinit:/docker-entrypoint-initdb.d:ro

  nginx:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile_nginx
    ports:
      - 8080:8080
    depends_on:
      - soveltuvuustesti-rahti
 
